# Generated by Django 4.1.3 on 2022-11-26 19:42

from django.db import migrations

def populate_status(apps, schemaeditor):
    statuses = {
        "published": "post that has been published",
        "draft": "A post that has not been published"
    }
    Status = apps.get_model("posts", "Status")
    for name, desc in statuses.items(): #library that retrieves status
        status_obj =Status(name=name, description=desc)
        status_obj.save() # creating status object by instantiating new status object


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
